### ISSUE TITLE
Proposed API change; NSErrors instead of NSExceptions

### ISSUE THREAD

**Issue by alexkent** [evsinev/BerTlv#4]
Hi evsinev!
Me and my colleagues use your project for our TLV needs and find it excellent. Though we have ran into an issue which is causing our apps to crash.

The library uses NSExceptions to indicate errors. We can of course add try catch statements to our own code but we thought we’d fix it in the library since we believe that the use of exceptions in Objective-C is a bit unconventional (and so not expected by users of the library).
As stated here in Apple’s documentation about [dealing with Errors](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/ErrorHandling/ErrorHandling.html), you're only supposed to use exceptions for programmer errors and I would argue that a library that parses data shouldn’t throw exceptions when the data is not correct since it’s the input data is seldom static and is received from somewhere or someone else.

I’d be happy to submit a pull request to mitigate this. I see there are some options on how to make this change;

- Add an additional method for each method that throws exceptions and catch the exceptions there and use NSErrors. This option would be the least intrusive to existing users of this API (but leave the potential 'unexpected need for try catch' problem with the existing API).

- Change the existing public API, add NSError parameter to each method. Thus requiring all users of the library to migrate to this pattern.

- Not change the public API at all, just wrap all the exceptions, log a message and return nil. This is the least effort for us! Because it'll silently fix crashers in our app without any changes in our code. But, silently changing behaviour of an API is not usually a good idea. 

What do you think?

**Comment by evsinev** [comment]
Hi alexkent,

We also faced with this problem.

We have a few methods which throws an exception:
- BerTlvBuilder: (NSData *)createLengthData:(NSUInteger)aLength
- BerTlvBuilder: (NSUInteger) calcBytesCountForLength:(NSUInteger)aLength
- BerTlv: (void)checkPrimitive
- HexUtil: (NSData *)parse:(NSString *)aHex
- BerTlvParser: (BerTlv *)parseWithResult
- BerTlvParser: (uint) calcDataLength:(NSData *)aBuf offset:(uint) aOffset

In our applications we have many usages of the HexUtil.parse method.
Other methods are used not so often. 

I this we can use two options:
1. Remove an exception from a method but return nil if something wrong. 
Also add another method with NSError argument.
It can be applied to HexUtil.parse:
- HexUtil.parse will return nil if error
- HexUril.parse:error with NSError parameter

2. For other methods we add NSError as a parameter.

**Comment by alexkent** [comment]
ok great.
I'm working on the change now, one question came up during implementation: 

In BerTlvParser when parsing malformed data, if we hit an error after successfully parsing a some tags, alongside there error pointer, should we return nil or should we return the partial result?

**Comment by evsinev** [comment]
> In BerTlvParser when parsing malformed data, if we hit an error after successfully parsing a some tags, alongside there error pointer, should we return nil or should we return the partial result?
I this we should return nil and parser method would be only with NSError parameter. It's ok if it will break API.

**Comment by Krillsson** [comment]
Great work @alexkent! @evsinev, would you mind making another release?

**Comment by alexkent** [comment]
i have a couple more changes for your consideration @evsinev before a release. i'll post another pull request very soon.

**Comment by orbisonitrum** [comment]
@evsinev could you please make a new release with the latest changes concerning this as well? Much appreciated!

**Comment by evsinev** [comment]
@orbisonitrum I've released 0.2.1 version. Sorry for the delay (was with pour internet connection).

**Comment by evsinev** [comment]
Thanks a lot!
